# Generated by Django 3.2 on 2023-06-24 15:49
import json
import os
from django.db import migrations
from conf.settings.django import BASE_DIR


def upload_ingredients(apps, schema_editor):
    Ingredient = apps.get_model("models_app", "Ingredient")
    with open(
        os.path.join(BASE_DIR, "upload_ingredients", "ingredients.json"),
        "r", encoding="UTF-8"
    ) as file:
        data = json.loads(file.read())
        for ingredient in data:
            Ingredient.objects.get_or_create(
                name=ingredient["name"],
                measurement_unit=ingredient["measurement_unit"]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(upload_ingredients),
    ]
