# Generated by Django 4.0 on 2023-06-20 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0004_alter_subscription_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='list_authors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи на которых подписан'),
        ),
    ]
