# Generated by Django 4.0 on 2023-06-22 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alter_ingredientamount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='models_app.Recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='list_authors', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, на которых подписан'),
        ),
    ]
