# Generated by Django 4.0 on 2023-06-22 10:18
import json
import os

from django.db import migrations

from conf.settings.django import BASE_DIR


def upload_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('models_app', 'Ingredient')
    with open(os.path.join(
            BASE_DIR,
            "utils",
            "ingredients.json"
    ), "r", encoding="UTF-8") as file:
        for ingredient in json.loads(file.read()):
            Ingredient.objects.get_or_create(
                name=ingredient["name"],
                measurement_unit=ingredient["measurement_unit"]
            )


class Migration(migrations.Migration):
    dependencies = [
        ('models_app', '0007_alter_shoppinglist_recipes_and_more'),
    ]

    operations = [
        migrations.RunPython(upload_ingredients),
    ]
