# Generated by Django 3.2 on 2023-04-09 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Tag',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('name', models.TextField(unique=True, verbose_name='Название')),
    #             ('color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет')),
    #             ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
    #         ],
    #         options={
    #             'verbose_name': 'Тэг',
    #             'verbose_name_plural': 'Тэги',
    #         },
    #     ),
    #     migrations.CreateModel(
    #         name='Recipe',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('name', models.CharField(max_length=16)),
    #             ('cooking_time', models.IntegerField(blank=True, default=1, null=True, verbose_name='Время приготовления')),
    #             ('image', models.ImageField(blank=True, upload_to='recipe/', verbose_name='Картинка')),
    #             ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
    #             ('ingredients', models.CharField(max_length=256, verbose_name='Название')),
    #             ('text', models.TextField(blank=True, max_length=256, verbose_name='Описание')),
    #             ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
    #             ('tags', models.ManyToManyField(help_text='Тэг, к которому относится рецепт', related_name='recipes', to='recipes.Tag', verbose_name='Тэг рецепта')),
    #         ],
    #     ),
    # ]
