# Generated by Django 3.2 on 2023-04-14 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_initial'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='ingredientamount',
    #         old_name='ingredient',
    #         new_name='recipe_ingredient',
    #     ),
    # ]
