# Generated by Django 3.2 on 2023-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_ingredient_ingredientamount_recipe_ingredient'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='ingredientamount',
    #         name='amount',
    #         field=models.CharField(max_length=156),
    #     ),
    # ]
