# Generated by Django 3.2 on 2023-04-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0015_follow_ingredient_ingredientamount_recipe_shoppingcart_tag_tagrecipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='recipe',
    #         name='author',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
    #     ),
    #     migrations.AddField(
    #         model_name='recipe',
    #         name='tags',
    #         field=models.ManyToManyField(to='recipes.Tag', verbose_name='Список тегов'),
    #     ),
    #     migrations.AddField(
    #         model_name='ingredientamount',
    #         name='name',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.ingredient', verbose_name='Ингредиент'),
    #     ),
    #     migrations.AddField(
    #         model_name='ingredientamount',
    #         name='recipe',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='Рецепт'),
    #     ),
    #     migrations.AddField(
    #         model_name='follow',
    #         name='following',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Автор блога'),
    #     ),
    #     migrations.AddField(
    #         model_name='follow',
    #         name='user',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
    #     ),
    #     migrations.AddConstraint(
    #         model_name='recipe',
    #         constraint=models.UniqueConstraint(fields=('author', 'name'), name='author_recipe_unique'),
    #     ),
    #     migrations.AddConstraint(
    #         model_name='follow',
    #         constraint=models.UniqueConstraint(fields=('user', 'following'), name='Подписчик'),
    #     ),
    # ]
