# Generated by Django 3.2 on 2023-04-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230406_1409'),
    ]

    # operations = [
    #     migrations.AlterModelOptions(
    #         name='userprofile',
    #         options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
    #     ),
    # ]
