# Generated by Django 3.2 on 2023-04-15 09:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_options'),
    ]

    # operations = [
    #     migrations.AlterModelOptions(
    #         name='userprofile',
    #         options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='email',
    #         field=models.EmailField(error_messages={'unique': 'Такой email уже используется.'}, max_length=254, unique=True, verbose_name='email'),
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='first_name',
    #         field=models.CharField(blank=True, max_length=150, null=True, verbose_name='first name'),
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='last_name',
    #         field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last name'),
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='username',
    #         field=models.CharField(error_messages={'unique': 'Такой пользователь уже зарегистрирован'}, help_text='Обязательно к заполнению. <=150 символов. Только буквы, цифры и @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
    #     ),
    #     migrations.AddConstraint(
    #         model_name='userprofile',
    #         constraint=models.CheckConstraint(check=models.Q(_negated=True, username='me'), name='no_me'),
    #     ),
    # ]
