# Generated by Django 3.2 on 2023-04-17 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230415_0958'),
    ]

    # operations = [
    #     migrations.AlterModelOptions(
    #         name='userprofile',
    #         options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
    #     ),
    #     migrations.RemoveConstraint(
    #         model_name='userprofile',
    #         name='no_me',
    #     ),
    # ]
