# Generated by Django 3.2 on 2023-04-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile'),
    ]

    # operations = [
    #     migrations.AlterModelOptions(
    #         name='userprofile',
    #         options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
    #     ),
    #     migrations.AddField(
    #         model_name='userprofile',
    #         name='is_subscribed',
    #         field=models.BooleanField(default=False, verbose_name='is_subscribed'),
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='first_name',
    #         field=models.CharField(max_length=150, verbose_name='first name'),
    #     ),
    #     migrations.AlterField(
    #         model_name='userprofile',
    #         name='password',
    #         field=models.CharField(max_length=150, verbose_name='password'),
    #     ),
    # ]
